name: lightsServer
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2022.10.11
  - dataclasses=0.8
  - flask-cors=3.0.10
  - itsdangerous=2.0.1
  - libffi=3.4.2
  - ncurses=6.3
  - openssl=1.1.1s
  - python=3.10.8
  - readline=8.2
  - six=1.16.0
  - sqlite=3.40.0
  - tk=8.6.12
  - tzdata=2022g
  - werkzeug=2.0.3
  - wheel=0.37.1
  - xz=5.2.8
  - zlib=1.2.13
  - pip:
    - certifi==2022.9.24
    - click==8.0.4
    - flask==2.1.3
    - flask_sqlalchemy
    - jinja2==3.1.2
    - markupsafe==2.1.1
    - pip==22.3.1
    - setuptools==65.5.0
